import type { Metadata } from "next";
import type { NextFontWithVariable } from "next/dist/compiled/@next/font";
import type { FC, ReactNode } from 'react';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans: NextFontWithVariable = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono: NextFontWithVariable = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({
    children,
}: Readonly<RootLayoutProps>) => {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
